### ISSUE TITLE
Mobile: Whilo logo on mobile skewed & too big (Home & Vid Detail pages)

### ISSUE THREAD

**Issue by tyleruniform** [WhiloApp/Whilo#18]
![IMG_5448](https://user-images.githubusercontent.com/54255992/71826518-6a9f1d00-309e-11ea-8c95-230585206027.PNG)

**Comment by tyleruniform** [comment]
When rotating your phone, the logo is MUCH too large and skewed (see above)...

**Comment by dominicphillips** [comment]
Can't reproduce
